package com.dao.mapper;

import com.dao.beans.AppCode;
import com.dao.beans.AppCodeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AppCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    long countByExample(AppCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int deleteByExample(AppCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int insert(AppCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int insertSelective(AppCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    List<AppCode> selectByExample(AppCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    AppCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppCode record, @Param("example") AppCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppCode record, @Param("example") AppCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppCode record);
}