package com.dao.mapper;

import java.util.List;
import com.dao.beans.MtOrderLog;
import com.dao.beans.MtOrderLogExample;
import org.apache.ibatis.annotations.Param;

public interface MtOrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    long countByExample(MtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int deleteByExample(MtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int insert(MtOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int insertSelective(MtOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    List<MtOrderLog> selectByExampleWithBLOBs(MtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    List<MtOrderLog> selectByExample(MtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    MtOrderLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MtOrderLog record, @Param("example") MtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MtOrderLog record, @Param("example") MtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MtOrderLog record, @Param("example") MtOrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MtOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MtOrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mt_order_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MtOrderLog record);
}