package com.dao.mapper;

import com.dao.beans.StudyPlan;
import com.dao.beans.StudyPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudyPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    long countByExample(StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int deleteByExample(StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer _id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int insert(StudyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int insertSelective(StudyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    List<StudyPlan> selectByExample(StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    StudyPlan selectByPrimaryKey(Integer _id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StudyPlan record, @Param("example") StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StudyPlan record, @Param("example") StudyPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudyPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StudyPlan record);
}