server:
  port: 8066
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://140.143.98.124:3306/springboot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    request-context-attribute: request
    cache: false
  #rabbitmq:
   # host: 127.0.0.1
   # port: 5672
   # username: rabbit
   # password: 123
   # publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
mybatis:
  config-locations:
    classpath: mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
shiro:
  userNativeSessionManager: true