package com.dao.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _account
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _account
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _account
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _account
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _account
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("_userName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("_userName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("_userName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("_userName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("_userName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("_userName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("_userName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("_userName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("_userName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("_userName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("_userName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("_userName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("_userName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("_userName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andAgidIsNull() {
            addCriterion("_agId is null");
            return (Criteria) this;
        }

        public Criteria andAgidIsNotNull() {
            addCriterion("_agId is not null");
            return (Criteria) this;
        }

        public Criteria andAgidEqualTo(Integer value) {
            addCriterion("_agId =", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidNotEqualTo(Integer value) {
            addCriterion("_agId <>", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidGreaterThan(Integer value) {
            addCriterion("_agId >", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidGreaterThanOrEqualTo(Integer value) {
            addCriterion("_agId >=", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidLessThan(Integer value) {
            addCriterion("_agId <", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidLessThanOrEqualTo(Integer value) {
            addCriterion("_agId <=", value, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidIn(List<Integer> values) {
            addCriterion("_agId in", values, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidNotIn(List<Integer> values) {
            addCriterion("_agId not in", values, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidBetween(Integer value1, Integer value2) {
            addCriterion("_agId between", value1, value2, "agid");
            return (Criteria) this;
        }

        public Criteria andAgidNotBetween(Integer value1, Integer value2) {
            addCriterion("_agId not between", value1, value2, "agid");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("_pwd is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("_pwd =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("_pwd <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("_pwd >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("_pwd >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("_pwd <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("_pwd <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("_pwd like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("_pwd not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("_pwd in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("_pwd not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("_pwd between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("_pwd not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNull() {
            addCriterion("_roleId is null");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("_roleId is not null");
            return (Criteria) this;
        }

        public Criteria andRoleidEqualTo(Integer value) {
            addCriterion("_roleId =", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotEqualTo(Integer value) {
            addCriterion("_roleId <>", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThan(Integer value) {
            addCriterion("_roleId >", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(Integer value) {
            addCriterion("_roleId >=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThan(Integer value) {
            addCriterion("_roleId <", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThanOrEqualTo(Integer value) {
            addCriterion("_roleId <=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidIn(List<Integer> values) {
            addCriterion("_roleId in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotIn(List<Integer> values) {
            addCriterion("_roleId not in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidBetween(Integer value1, Integer value2) {
            addCriterion("_roleId between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotBetween(Integer value1, Integer value2) {
            addCriterion("_roleId not between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("_salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("_salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("_salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("_salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("_salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("_salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("_salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("_salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("_salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("_salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("_salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("_salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("_salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("_salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andPlattypeIsNull() {
            addCriterion("_platType is null");
            return (Criteria) this;
        }

        public Criteria andPlattypeIsNotNull() {
            addCriterion("_platType is not null");
            return (Criteria) this;
        }

        public Criteria andPlattypeEqualTo(Integer value) {
            addCriterion("_platType =", value, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeNotEqualTo(Integer value) {
            addCriterion("_platType <>", value, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeGreaterThan(Integer value) {
            addCriterion("_platType >", value, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("_platType >=", value, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeLessThan(Integer value) {
            addCriterion("_platType <", value, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeLessThanOrEqualTo(Integer value) {
            addCriterion("_platType <=", value, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeIn(List<Integer> values) {
            addCriterion("_platType in", values, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeNotIn(List<Integer> values) {
            addCriterion("_platType not in", values, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeBetween(Integer value1, Integer value2) {
            addCriterion("_platType between", value1, value2, "plattype");
            return (Criteria) this;
        }

        public Criteria andPlattypeNotBetween(Integer value1, Integer value2) {
            addCriterion("_platType not between", value1, value2, "plattype");
            return (Criteria) this;
        }

        public Criteria andUseremailIsNull() {
            addCriterion("_userEmail is null");
            return (Criteria) this;
        }

        public Criteria andUseremailIsNotNull() {
            addCriterion("_userEmail is not null");
            return (Criteria) this;
        }

        public Criteria andUseremailEqualTo(String value) {
            addCriterion("_userEmail =", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotEqualTo(String value) {
            addCriterion("_userEmail <>", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailGreaterThan(String value) {
            addCriterion("_userEmail >", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailGreaterThanOrEqualTo(String value) {
            addCriterion("_userEmail >=", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLessThan(String value) {
            addCriterion("_userEmail <", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLessThanOrEqualTo(String value) {
            addCriterion("_userEmail <=", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailLike(String value) {
            addCriterion("_userEmail like", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotLike(String value) {
            addCriterion("_userEmail not like", value, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailIn(List<String> values) {
            addCriterion("_userEmail in", values, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotIn(List<String> values) {
            addCriterion("_userEmail not in", values, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailBetween(String value1, String value2) {
            addCriterion("_userEmail between", value1, value2, "useremail");
            return (Criteria) this;
        }

        public Criteria andUseremailNotBetween(String value1, String value2) {
            addCriterion("_userEmail not between", value1, value2, "useremail");
            return (Criteria) this;
        }

        public Criteria andUsermobileIsNull() {
            addCriterion("_userMobile is null");
            return (Criteria) this;
        }

        public Criteria andUsermobileIsNotNull() {
            addCriterion("_userMobile is not null");
            return (Criteria) this;
        }

        public Criteria andUsermobileEqualTo(String value) {
            addCriterion("_userMobile =", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileNotEqualTo(String value) {
            addCriterion("_userMobile <>", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileGreaterThan(String value) {
            addCriterion("_userMobile >", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileGreaterThanOrEqualTo(String value) {
            addCriterion("_userMobile >=", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileLessThan(String value) {
            addCriterion("_userMobile <", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileLessThanOrEqualTo(String value) {
            addCriterion("_userMobile <=", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileLike(String value) {
            addCriterion("_userMobile like", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileNotLike(String value) {
            addCriterion("_userMobile not like", value, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileIn(List<String> values) {
            addCriterion("_userMobile in", values, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileNotIn(List<String> values) {
            addCriterion("_userMobile not in", values, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileBetween(String value1, String value2) {
            addCriterion("_userMobile between", value1, value2, "usermobile");
            return (Criteria) this;
        }

        public Criteria andUsermobileNotBetween(String value1, String value2) {
            addCriterion("_userMobile not between", value1, value2, "usermobile");
            return (Criteria) this;
        }

        public Criteria andLogincountIsNull() {
            addCriterion("_loginCount is null");
            return (Criteria) this;
        }

        public Criteria andLogincountIsNotNull() {
            addCriterion("_loginCount is not null");
            return (Criteria) this;
        }

        public Criteria andLogincountEqualTo(Integer value) {
            addCriterion("_loginCount =", value, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountNotEqualTo(Integer value) {
            addCriterion("_loginCount <>", value, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountGreaterThan(Integer value) {
            addCriterion("_loginCount >", value, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountGreaterThanOrEqualTo(Integer value) {
            addCriterion("_loginCount >=", value, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountLessThan(Integer value) {
            addCriterion("_loginCount <", value, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountLessThanOrEqualTo(Integer value) {
            addCriterion("_loginCount <=", value, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountIn(List<Integer> values) {
            addCriterion("_loginCount in", values, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountNotIn(List<Integer> values) {
            addCriterion("_loginCount not in", values, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountBetween(Integer value1, Integer value2) {
            addCriterion("_loginCount between", value1, value2, "logincount");
            return (Criteria) this;
        }

        public Criteria andLogincountNotBetween(Integer value1, Integer value2) {
            addCriterion("_loginCount not between", value1, value2, "logincount");
            return (Criteria) this;
        }

        public Criteria andAnothernameIsNull() {
            addCriterion("_anotherName is null");
            return (Criteria) this;
        }

        public Criteria andAnothernameIsNotNull() {
            addCriterion("_anotherName is not null");
            return (Criteria) this;
        }

        public Criteria andAnothernameEqualTo(String value) {
            addCriterion("_anotherName =", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameNotEqualTo(String value) {
            addCriterion("_anotherName <>", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameGreaterThan(String value) {
            addCriterion("_anotherName >", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameGreaterThanOrEqualTo(String value) {
            addCriterion("_anotherName >=", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameLessThan(String value) {
            addCriterion("_anotherName <", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameLessThanOrEqualTo(String value) {
            addCriterion("_anotherName <=", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameLike(String value) {
            addCriterion("_anotherName like", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameNotLike(String value) {
            addCriterion("_anotherName not like", value, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameIn(List<String> values) {
            addCriterion("_anotherName in", values, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameNotIn(List<String> values) {
            addCriterion("_anotherName not in", values, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameBetween(String value1, String value2) {
            addCriterion("_anotherName between", value1, value2, "anothername");
            return (Criteria) this;
        }

        public Criteria andAnothernameNotBetween(String value1, String value2) {
            addCriterion("_anotherName not between", value1, value2, "anothername");
            return (Criteria) this;
        }

        public Criteria andUserstatusIsNull() {
            addCriterion("_userStatus is null");
            return (Criteria) this;
        }

        public Criteria andUserstatusIsNotNull() {
            addCriterion("_userStatus is not null");
            return (Criteria) this;
        }

        public Criteria andUserstatusEqualTo(Integer value) {
            addCriterion("_userStatus =", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusNotEqualTo(Integer value) {
            addCriterion("_userStatus <>", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusGreaterThan(Integer value) {
            addCriterion("_userStatus >", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("_userStatus >=", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusLessThan(Integer value) {
            addCriterion("_userStatus <", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusLessThanOrEqualTo(Integer value) {
            addCriterion("_userStatus <=", value, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusIn(List<Integer> values) {
            addCriterion("_userStatus in", values, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusNotIn(List<Integer> values) {
            addCriterion("_userStatus not in", values, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusBetween(Integer value1, Integer value2) {
            addCriterion("_userStatus between", value1, value2, "userstatus");
            return (Criteria) this;
        }

        public Criteria andUserstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("_userStatus not between", value1, value2, "userstatus");
            return (Criteria) this;
        }

        public Criteria andLastloginIsNull() {
            addCriterion("_lastLogin is null");
            return (Criteria) this;
        }

        public Criteria andLastloginIsNotNull() {
            addCriterion("_lastLogin is not null");
            return (Criteria) this;
        }

        public Criteria andLastloginEqualTo(Date value) {
            addCriterion("_lastLogin =", value, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginNotEqualTo(Date value) {
            addCriterion("_lastLogin <>", value, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginGreaterThan(Date value) {
            addCriterion("_lastLogin >", value, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginGreaterThanOrEqualTo(Date value) {
            addCriterion("_lastLogin >=", value, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginLessThan(Date value) {
            addCriterion("_lastLogin <", value, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginLessThanOrEqualTo(Date value) {
            addCriterion("_lastLogin <=", value, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginIn(List<Date> values) {
            addCriterion("_lastLogin in", values, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginNotIn(List<Date> values) {
            addCriterion("_lastLogin not in", values, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginBetween(Date value1, Date value2) {
            addCriterion("_lastLogin between", value1, value2, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andLastloginNotBetween(Date value1, Date value2) {
            addCriterion("_lastLogin not between", value1, value2, "lastlogin");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("_createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("_createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("_createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("_createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("_createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("_createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("_createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("_createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("_createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("_createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("_Type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("_Type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("_Type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("_Type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("_Type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("_Type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("_Type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("_Type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("_Type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("_Type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("_Type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("_Type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andOptuseridIsNull() {
            addCriterion("_optUserId is null");
            return (Criteria) this;
        }

        public Criteria andOptuseridIsNotNull() {
            addCriterion("_optUserId is not null");
            return (Criteria) this;
        }

        public Criteria andOptuseridEqualTo(String value) {
            addCriterion("_optUserId =", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridNotEqualTo(String value) {
            addCriterion("_optUserId <>", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridGreaterThan(String value) {
            addCriterion("_optUserId >", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridGreaterThanOrEqualTo(String value) {
            addCriterion("_optUserId >=", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridLessThan(String value) {
            addCriterion("_optUserId <", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridLessThanOrEqualTo(String value) {
            addCriterion("_optUserId <=", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridLike(String value) {
            addCriterion("_optUserId like", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridNotLike(String value) {
            addCriterion("_optUserId not like", value, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridIn(List<String> values) {
            addCriterion("_optUserId in", values, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridNotIn(List<String> values) {
            addCriterion("_optUserId not in", values, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridBetween(String value1, String value2) {
            addCriterion("_optUserId between", value1, value2, "optuserid");
            return (Criteria) this;
        }

        public Criteria andOptuseridNotBetween(String value1, String value2) {
            addCriterion("_optUserId not between", value1, value2, "optuserid");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("_realName is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("_realName is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("_realName =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("_realName <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("_realName >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("_realName >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("_realName <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("_realName <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("_realName like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("_realName not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("_realName in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("_realName not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("_realName between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("_realName not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("_remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("_remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("_remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("_remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("_remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("_remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("_remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("_remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("_remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("_remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("_remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("_remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("_remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("_remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeIsNull() {
            addCriterion("app_poi_code is null");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeIsNotNull() {
            addCriterion("app_poi_code is not null");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeEqualTo(String value) {
            addCriterion("app_poi_code =", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotEqualTo(String value) {
            addCriterion("app_poi_code <>", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeGreaterThan(String value) {
            addCriterion("app_poi_code >", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeGreaterThanOrEqualTo(String value) {
            addCriterion("app_poi_code >=", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeLessThan(String value) {
            addCriterion("app_poi_code <", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeLessThanOrEqualTo(String value) {
            addCriterion("app_poi_code <=", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeLike(String value) {
            addCriterion("app_poi_code like", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotLike(String value) {
            addCriterion("app_poi_code not like", value, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeIn(List<String> values) {
            addCriterion("app_poi_code in", values, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotIn(List<String> values) {
            addCriterion("app_poi_code not in", values, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeBetween(String value1, String value2) {
            addCriterion("app_poi_code between", value1, value2, "appPoiCode");
            return (Criteria) this;
        }

        public Criteria andAppPoiCodeNotBetween(String value1, String value2) {
            addCriterion("app_poi_code not between", value1, value2, "appPoiCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _account
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _account
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}