package com.dao.beans;

public class AppCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.port
     *
     * @mbg.generated
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.db_id
     *
     * @mbg.generated
     */
    private String dbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.db_name
     *
     * @mbg.generated
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.app_poi_code
     *
     * @mbg.generated
     */
    private String appPoiCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_code.app_secret
     *
     * @mbg.generated
     */
    private String appSecret;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.id
     *
     * @return the value of app_code.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.id
     *
     * @param id the value for app_code.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.port
     *
     * @return the value of app_code.port
     *
     * @mbg.generated
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.port
     *
     * @param port the value for app_code.port
     *
     * @mbg.generated
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.db_id
     *
     * @return the value of app_code.db_id
     *
     * @mbg.generated
     */
    public String getDbId() {
        return dbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.db_id
     *
     * @param dbId the value for app_code.db_id
     *
     * @mbg.generated
     */
    public void setDbId(String dbId) {
        this.dbId = dbId == null ? null : dbId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.db_name
     *
     * @return the value of app_code.db_name
     *
     * @mbg.generated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.db_name
     *
     * @param dbName the value for app_code.db_name
     *
     * @mbg.generated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.shop_id
     *
     * @return the value of app_code.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.shop_id
     *
     * @param shopId the value for app_code.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.app_poi_code
     *
     * @return the value of app_code.app_poi_code
     *
     * @mbg.generated
     */
    public String getAppPoiCode() {
        return appPoiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.app_poi_code
     *
     * @param appPoiCode the value for app_code.app_poi_code
     *
     * @mbg.generated
     */
    public void setAppPoiCode(String appPoiCode) {
        this.appPoiCode = appPoiCode == null ? null : appPoiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.shop_name
     *
     * @return the value of app_code.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.shop_name
     *
     * @param shopName the value for app_code.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.app_id
     *
     * @return the value of app_code.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.app_id
     *
     * @param appId the value for app_code.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_code.app_secret
     *
     * @return the value of app_code.app_secret
     *
     * @mbg.generated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_code.app_secret
     *
     * @param appSecret the value for app_code.app_secret
     *
     * @mbg.generated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }
}