package com.dao.beans;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class MtCompletedOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.jjy_bill_id
     *
     * @mbg.generated
     */
    private String jjyBillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.order_create_time
     *
     * @mbg.generated
     */
    private Date orderCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.order_completed_time
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date orderCompletedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.wm_order_id_view
     *
     * @mbg.generated
     */
    private String wmOrderIdView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.app_poi_code
     *
     * @mbg.generated
     */
    private String appPoiCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.wm_poi_id
     *
     * @mbg.generated
     */
    private String wmPoiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.wm_poi_name
     *
     * @mbg.generated
     */
    private String wmPoiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.wm_poi_address
     *
     * @mbg.generated
     */
    private String wmPoiAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.wm_poi_phone
     *
     * @mbg.generated
     */
    private String wmPoiPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.recipient_address
     *
     * @mbg.generated
     */
    private String recipientAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.recipient_phone
     *
     * @mbg.generated
     */
    private String recipientPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.recipient_name
     *
     * @mbg.generated
     */
    private String recipientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.shipping_fee
     *
     * @mbg.generated
     */
    private String shippingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.total
     *
     * @mbg.generated
     */
    private String total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.original_price
     *
     * @mbg.generated
     */
    private String originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.caution
     *
     * @mbg.generated
     */
    private String caution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.shipper_phone
     *
     * @mbg.generated
     */
    private String shipperPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.has_invoiced
     *
     * @mbg.generated
     */
    private String hasInvoiced;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.invoice_title
     *
     * @mbg.generated
     */
    private String invoiceTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.taxpayer_id
     *
     * @mbg.generated
     */
    private String taxpayerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.ctime
     *
     * @mbg.generated
     */
    private String ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.utime
     *
     * @mbg.generated
     */
    private String utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.delivery_time
     *
     * @mbg.generated
     */
    private String deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.is_third_shipping
     *
     * @mbg.generated
     */
    private String isThirdShipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.pay_type
     *
     * @mbg.generated
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.pick_type
     *
     * @mbg.generated
     */
    private String pickType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.latitude
     *
     * @mbg.generated
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.longitude
     *
     * @mbg.generated
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.day_seq
     *
     * @mbg.generated
     */
    private String daySeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.is_favorites
     *
     * @mbg.generated
     */
    private String isFavorites;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.is_poi_first_order
     *
     * @mbg.generated
     */
    private String isPoiFirstOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.dinners_number
     *
     * @mbg.generated
     */
    private String dinnersNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.logistics_code
     *
     * @mbg.generated
     */
    private String logisticsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.avg_send_time
     *
     * @mbg.generated
     */
    private String avgSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.package_bag_money
     *
     * @mbg.generated
     */
    private String packageBagMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.sig
     *
     * @mbg.generated
     */
    private String sig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.jjy_order_type
     *
     * @mbg.generated
     */
    private Integer jjyOrderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.jjy_diff_type
     *
     * @mbg.generated
     */
    private Integer jjyDiffType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.jjy_push_type
     *
     * @mbg.generated
     */
    private Integer jjyPushType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.total_tmp
     *
     * @mbg.generated
     */
    private String totalTmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.original_price_tmp
     *
     * @mbg.generated
     */
    private String originalPriceTmp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.create_time
     *
     * @mbg.generated
     */

    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mt_completed_order.json_data
     *
     * @mbg.generated
     */
    private String jsonData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.id
     *
     * @return the value of mt_completed_order.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.id
     *
     * @param id the value for mt_completed_order.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.jjy_bill_id
     *
     * @return the value of mt_completed_order.jjy_bill_id
     *
     * @mbg.generated
     */
    public String getJjyBillId() {
        return jjyBillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.jjy_bill_id
     *
     * @param jjyBillId the value for mt_completed_order.jjy_bill_id
     *
     * @mbg.generated
     */
    public void setJjyBillId(String jjyBillId) {
        this.jjyBillId = jjyBillId == null ? null : jjyBillId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.order_id
     *
     * @return the value of mt_completed_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.order_id
     *
     * @param orderId the value for mt_completed_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.order_create_time
     *
     * @return the value of mt_completed_order.order_create_time
     *
     * @mbg.generated
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.order_create_time
     *
     * @param orderCreateTime the value for mt_completed_order.order_create_time
     *
     * @mbg.generated
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.order_completed_time
     *
     * @return the value of mt_completed_order.order_completed_time
     *
     * @mbg.generated
     */
    public Date getOrderCompletedTime() {
        return orderCompletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.order_completed_time
     *
     * @param orderCompletedTime the value for mt_completed_order.order_completed_time
     *
     * @mbg.generated
     */
    public void setOrderCompletedTime(Date orderCompletedTime) {
        this.orderCompletedTime = orderCompletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.wm_order_id_view
     *
     * @return the value of mt_completed_order.wm_order_id_view
     *
     * @mbg.generated
     */
    public String getWmOrderIdView() {
        return wmOrderIdView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.wm_order_id_view
     *
     * @param wmOrderIdView the value for mt_completed_order.wm_order_id_view
     *
     * @mbg.generated
     */
    public void setWmOrderIdView(String wmOrderIdView) {
        this.wmOrderIdView = wmOrderIdView == null ? null : wmOrderIdView.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.app_id
     *
     * @return the value of mt_completed_order.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.app_id
     *
     * @param appId the value for mt_completed_order.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.app_poi_code
     *
     * @return the value of mt_completed_order.app_poi_code
     *
     * @mbg.generated
     */
    public String getAppPoiCode() {
        return appPoiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.app_poi_code
     *
     * @param appPoiCode the value for mt_completed_order.app_poi_code
     *
     * @mbg.generated
     */
    public void setAppPoiCode(String appPoiCode) {
        this.appPoiCode = appPoiCode == null ? null : appPoiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.wm_poi_id
     *
     * @return the value of mt_completed_order.wm_poi_id
     *
     * @mbg.generated
     */
    public String getWmPoiId() {
        return wmPoiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.wm_poi_id
     *
     * @param wmPoiId the value for mt_completed_order.wm_poi_id
     *
     * @mbg.generated
     */
    public void setWmPoiId(String wmPoiId) {
        this.wmPoiId = wmPoiId == null ? null : wmPoiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.wm_poi_name
     *
     * @return the value of mt_completed_order.wm_poi_name
     *
     * @mbg.generated
     */
    public String getWmPoiName() {
        return wmPoiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.wm_poi_name
     *
     * @param wmPoiName the value for mt_completed_order.wm_poi_name
     *
     * @mbg.generated
     */
    public void setWmPoiName(String wmPoiName) {
        this.wmPoiName = wmPoiName == null ? null : wmPoiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.wm_poi_address
     *
     * @return the value of mt_completed_order.wm_poi_address
     *
     * @mbg.generated
     */
    public String getWmPoiAddress() {
        return wmPoiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.wm_poi_address
     *
     * @param wmPoiAddress the value for mt_completed_order.wm_poi_address
     *
     * @mbg.generated
     */
    public void setWmPoiAddress(String wmPoiAddress) {
        this.wmPoiAddress = wmPoiAddress == null ? null : wmPoiAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.wm_poi_phone
     *
     * @return the value of mt_completed_order.wm_poi_phone
     *
     * @mbg.generated
     */
    public String getWmPoiPhone() {
        return wmPoiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.wm_poi_phone
     *
     * @param wmPoiPhone the value for mt_completed_order.wm_poi_phone
     *
     * @mbg.generated
     */
    public void setWmPoiPhone(String wmPoiPhone) {
        this.wmPoiPhone = wmPoiPhone == null ? null : wmPoiPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.recipient_address
     *
     * @return the value of mt_completed_order.recipient_address
     *
     * @mbg.generated
     */
    public String getRecipientAddress() {
        return recipientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.recipient_address
     *
     * @param recipientAddress the value for mt_completed_order.recipient_address
     *
     * @mbg.generated
     */
    public void setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress == null ? null : recipientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.recipient_phone
     *
     * @return the value of mt_completed_order.recipient_phone
     *
     * @mbg.generated
     */
    public String getRecipientPhone() {
        return recipientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.recipient_phone
     *
     * @param recipientPhone the value for mt_completed_order.recipient_phone
     *
     * @mbg.generated
     */
    public void setRecipientPhone(String recipientPhone) {
        this.recipientPhone = recipientPhone == null ? null : recipientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.recipient_name
     *
     * @return the value of mt_completed_order.recipient_name
     *
     * @mbg.generated
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.recipient_name
     *
     * @param recipientName the value for mt_completed_order.recipient_name
     *
     * @mbg.generated
     */
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName == null ? null : recipientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.shipping_fee
     *
     * @return the value of mt_completed_order.shipping_fee
     *
     * @mbg.generated
     */
    public String getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.shipping_fee
     *
     * @param shippingFee the value for mt_completed_order.shipping_fee
     *
     * @mbg.generated
     */
    public void setShippingFee(String shippingFee) {
        this.shippingFee = shippingFee == null ? null : shippingFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.total
     *
     * @return the value of mt_completed_order.total
     *
     * @mbg.generated
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.total
     *
     * @param total the value for mt_completed_order.total
     *
     * @mbg.generated
     */
    public void setTotal(String total) {
        this.total = total == null ? null : total.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.original_price
     *
     * @return the value of mt_completed_order.original_price
     *
     * @mbg.generated
     */
    public String getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.original_price
     *
     * @param originalPrice the value for mt_completed_order.original_price
     *
     * @mbg.generated
     */
    public void setOriginalPrice(String originalPrice) {
        this.originalPrice = originalPrice == null ? null : originalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.caution
     *
     * @return the value of mt_completed_order.caution
     *
     * @mbg.generated
     */
    public String getCaution() {
        return caution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.caution
     *
     * @param caution the value for mt_completed_order.caution
     *
     * @mbg.generated
     */
    public void setCaution(String caution) {
        this.caution = caution == null ? null : caution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.shipper_phone
     *
     * @return the value of mt_completed_order.shipper_phone
     *
     * @mbg.generated
     */
    public String getShipperPhone() {
        return shipperPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.shipper_phone
     *
     * @param shipperPhone the value for mt_completed_order.shipper_phone
     *
     * @mbg.generated
     */
    public void setShipperPhone(String shipperPhone) {
        this.shipperPhone = shipperPhone == null ? null : shipperPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.status
     *
     * @return the value of mt_completed_order.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.status
     *
     * @param status the value for mt_completed_order.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.city_id
     *
     * @return the value of mt_completed_order.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.city_id
     *
     * @param cityId the value for mt_completed_order.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.has_invoiced
     *
     * @return the value of mt_completed_order.has_invoiced
     *
     * @mbg.generated
     */
    public String getHasInvoiced() {
        return hasInvoiced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.has_invoiced
     *
     * @param hasInvoiced the value for mt_completed_order.has_invoiced
     *
     * @mbg.generated
     */
    public void setHasInvoiced(String hasInvoiced) {
        this.hasInvoiced = hasInvoiced == null ? null : hasInvoiced.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.invoice_title
     *
     * @return the value of mt_completed_order.invoice_title
     *
     * @mbg.generated
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.invoice_title
     *
     * @param invoiceTitle the value for mt_completed_order.invoice_title
     *
     * @mbg.generated
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.taxpayer_id
     *
     * @return the value of mt_completed_order.taxpayer_id
     *
     * @mbg.generated
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.taxpayer_id
     *
     * @param taxpayerId the value for mt_completed_order.taxpayer_id
     *
     * @mbg.generated
     */
    public void setTaxpayerId(String taxpayerId) {
        this.taxpayerId = taxpayerId == null ? null : taxpayerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.ctime
     *
     * @return the value of mt_completed_order.ctime
     *
     * @mbg.generated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.ctime
     *
     * @param ctime the value for mt_completed_order.ctime
     *
     * @mbg.generated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.utime
     *
     * @return the value of mt_completed_order.utime
     *
     * @mbg.generated
     */
    public String getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.utime
     *
     * @param utime the value for mt_completed_order.utime
     *
     * @mbg.generated
     */
    public void setUtime(String utime) {
        this.utime = utime == null ? null : utime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.delivery_time
     *
     * @return the value of mt_completed_order.delivery_time
     *
     * @mbg.generated
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.delivery_time
     *
     * @param deliveryTime the value for mt_completed_order.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime == null ? null : deliveryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.is_third_shipping
     *
     * @return the value of mt_completed_order.is_third_shipping
     *
     * @mbg.generated
     */
    public String getIsThirdShipping() {
        return isThirdShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.is_third_shipping
     *
     * @param isThirdShipping the value for mt_completed_order.is_third_shipping
     *
     * @mbg.generated
     */
    public void setIsThirdShipping(String isThirdShipping) {
        this.isThirdShipping = isThirdShipping == null ? null : isThirdShipping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.pay_type
     *
     * @return the value of mt_completed_order.pay_type
     *
     * @mbg.generated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.pay_type
     *
     * @param payType the value for mt_completed_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.pick_type
     *
     * @return the value of mt_completed_order.pick_type
     *
     * @mbg.generated
     */
    public String getPickType() {
        return pickType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.pick_type
     *
     * @param pickType the value for mt_completed_order.pick_type
     *
     * @mbg.generated
     */
    public void setPickType(String pickType) {
        this.pickType = pickType == null ? null : pickType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.latitude
     *
     * @return the value of mt_completed_order.latitude
     *
     * @mbg.generated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.latitude
     *
     * @param latitude the value for mt_completed_order.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.longitude
     *
     * @return the value of mt_completed_order.longitude
     *
     * @mbg.generated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.longitude
     *
     * @param longitude the value for mt_completed_order.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.day_seq
     *
     * @return the value of mt_completed_order.day_seq
     *
     * @mbg.generated
     */
    public String getDaySeq() {
        return daySeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.day_seq
     *
     * @param daySeq the value for mt_completed_order.day_seq
     *
     * @mbg.generated
     */
    public void setDaySeq(String daySeq) {
        this.daySeq = daySeq == null ? null : daySeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.is_favorites
     *
     * @return the value of mt_completed_order.is_favorites
     *
     * @mbg.generated
     */
    public String getIsFavorites() {
        return isFavorites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.is_favorites
     *
     * @param isFavorites the value for mt_completed_order.is_favorites
     *
     * @mbg.generated
     */
    public void setIsFavorites(String isFavorites) {
        this.isFavorites = isFavorites == null ? null : isFavorites.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.is_poi_first_order
     *
     * @return the value of mt_completed_order.is_poi_first_order
     *
     * @mbg.generated
     */
    public String getIsPoiFirstOrder() {
        return isPoiFirstOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.is_poi_first_order
     *
     * @param isPoiFirstOrder the value for mt_completed_order.is_poi_first_order
     *
     * @mbg.generated
     */
    public void setIsPoiFirstOrder(String isPoiFirstOrder) {
        this.isPoiFirstOrder = isPoiFirstOrder == null ? null : isPoiFirstOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.dinners_number
     *
     * @return the value of mt_completed_order.dinners_number
     *
     * @mbg.generated
     */
    public String getDinnersNumber() {
        return dinnersNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.dinners_number
     *
     * @param dinnersNumber the value for mt_completed_order.dinners_number
     *
     * @mbg.generated
     */
    public void setDinnersNumber(String dinnersNumber) {
        this.dinnersNumber = dinnersNumber == null ? null : dinnersNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.logistics_code
     *
     * @return the value of mt_completed_order.logistics_code
     *
     * @mbg.generated
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.logistics_code
     *
     * @param logisticsCode the value for mt_completed_order.logistics_code
     *
     * @mbg.generated
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.avg_send_time
     *
     * @return the value of mt_completed_order.avg_send_time
     *
     * @mbg.generated
     */
    public String getAvgSendTime() {
        return avgSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.avg_send_time
     *
     * @param avgSendTime the value for mt_completed_order.avg_send_time
     *
     * @mbg.generated
     */
    public void setAvgSendTime(String avgSendTime) {
        this.avgSendTime = avgSendTime == null ? null : avgSendTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.package_bag_money
     *
     * @return the value of mt_completed_order.package_bag_money
     *
     * @mbg.generated
     */
    public String getPackageBagMoney() {
        return packageBagMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.package_bag_money
     *
     * @param packageBagMoney the value for mt_completed_order.package_bag_money
     *
     * @mbg.generated
     */
    public void setPackageBagMoney(String packageBagMoney) {
        this.packageBagMoney = packageBagMoney == null ? null : packageBagMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.sig
     *
     * @return the value of mt_completed_order.sig
     *
     * @mbg.generated
     */
    public String getSig() {
        return sig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.sig
     *
     * @param sig the value for mt_completed_order.sig
     *
     * @mbg.generated
     */
    public void setSig(String sig) {
        this.sig = sig == null ? null : sig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.jjy_order_type
     *
     * @return the value of mt_completed_order.jjy_order_type
     *
     * @mbg.generated
     */
    public Integer getJjyOrderType() {
        return jjyOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.jjy_order_type
     *
     * @param jjyOrderType the value for mt_completed_order.jjy_order_type
     *
     * @mbg.generated
     */
    public void setJjyOrderType(Integer jjyOrderType) {
        this.jjyOrderType = jjyOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.jjy_diff_type
     *
     * @return the value of mt_completed_order.jjy_diff_type
     *
     * @mbg.generated
     */
    public Integer getJjyDiffType() {
        return jjyDiffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.jjy_diff_type
     *
     * @param jjyDiffType the value for mt_completed_order.jjy_diff_type
     *
     * @mbg.generated
     */
    public void setJjyDiffType(Integer jjyDiffType) {
        this.jjyDiffType = jjyDiffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.jjy_push_type
     *
     * @return the value of mt_completed_order.jjy_push_type
     *
     * @mbg.generated
     */
    public Integer getJjyPushType() {
        return jjyPushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.jjy_push_type
     *
     * @param jjyPushType the value for mt_completed_order.jjy_push_type
     *
     * @mbg.generated
     */
    public void setJjyPushType(Integer jjyPushType) {
        this.jjyPushType = jjyPushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.total_tmp
     *
     * @return the value of mt_completed_order.total_tmp
     *
     * @mbg.generated
     */
    public String getTotalTmp() {
        return totalTmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.total_tmp
     *
     * @param totalTmp the value for mt_completed_order.total_tmp
     *
     * @mbg.generated
     */
    public void setTotalTmp(String totalTmp) {
        this.totalTmp = totalTmp == null ? null : totalTmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.original_price_tmp
     *
     * @return the value of mt_completed_order.original_price_tmp
     *
     * @mbg.generated
     */
    public String getOriginalPriceTmp() {
        return originalPriceTmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.original_price_tmp
     *
     * @param originalPriceTmp the value for mt_completed_order.original_price_tmp
     *
     * @mbg.generated
     */
    public void setOriginalPriceTmp(String originalPriceTmp) {
        this.originalPriceTmp = originalPriceTmp == null ? null : originalPriceTmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.create_time
     *
     * @return the value of mt_completed_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.create_time
     *
     * @param createTime the value for mt_completed_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_completed_order.json_data
     *
     * @return the value of mt_completed_order.json_data
     *
     * @mbg.generated
     */
    public String getJsonData() {
        return jsonData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_completed_order.json_data
     *
     * @param jsonData the value for mt_completed_order.json_data
     *
     * @mbg.generated
     */
    public void setJsonData(String jsonData) {
        this.jsonData = jsonData == null ? null : jsonData.trim();
    }
}