package com.dao.beans;

public class Permissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._authName
     *
     * @mbg.generated
     */
    private String authname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._parentId
     *
     * @mbg.generated
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _permissions._platType
     *
     * @mbg.generated
     */
    private Integer plattype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._id
     *
     * @return the value of _permissions._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._id
     *
     * @param id the value for _permissions._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._authName
     *
     * @return the value of _permissions._authName
     *
     * @mbg.generated
     */
    public String getAuthname() {
        return authname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._authName
     *
     * @param authname the value for _permissions._authName
     *
     * @mbg.generated
     */
    public void setAuthname(String authname) {
        this.authname = authname == null ? null : authname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._url
     *
     * @return the value of _permissions._url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._url
     *
     * @param url the value for _permissions._url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._parentId
     *
     * @return the value of _permissions._parentId
     *
     * @mbg.generated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._parentId
     *
     * @param parentid the value for _permissions._parentId
     *
     * @mbg.generated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._type
     *
     * @return the value of _permissions._type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._type
     *
     * @param type the value for _permissions._type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._method
     *
     * @return the value of _permissions._method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._method
     *
     * @param method the value for _permissions._method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._sort
     *
     * @return the value of _permissions._sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._sort
     *
     * @param sort the value for _permissions._sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._icon
     *
     * @return the value of _permissions._icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._icon
     *
     * @param icon the value for _permissions._icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._status
     *
     * @return the value of _permissions._status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._status
     *
     * @param status the value for _permissions._status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._path
     *
     * @return the value of _permissions._path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._path
     *
     * @param path the value for _permissions._path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _permissions._platType
     *
     * @return the value of _permissions._platType
     *
     * @mbg.generated
     */
    public Integer getPlattype() {
        return plattype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _permissions._platType
     *
     * @param plattype the value for _permissions._platType
     *
     * @mbg.generated
     */
    public void setPlattype(Integer plattype) {
        this.plattype = plattype;
    }
}