package com.dao.beans;

import java.util.ArrayList;
import java.util.List;

public class StudyPlanDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public StudyPlanDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdIsNull() {
            addCriterion("_study_plan_id is null");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdIsNotNull() {
            addCriterion("_study_plan_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdEqualTo(Integer value) {
            addCriterion("_study_plan_id =", value, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdNotEqualTo(Integer value) {
            addCriterion("_study_plan_id <>", value, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdGreaterThan(Integer value) {
            addCriterion("_study_plan_id >", value, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_study_plan_id >=", value, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdLessThan(Integer value) {
            addCriterion("_study_plan_id <", value, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdLessThanOrEqualTo(Integer value) {
            addCriterion("_study_plan_id <=", value, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdIn(List<Integer> values) {
            addCriterion("_study_plan_id in", values, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdNotIn(List<Integer> values) {
            addCriterion("_study_plan_id not in", values, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdBetween(Integer value1, Integer value2) {
            addCriterion("_study_plan_id between", value1, value2, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andStudyPlanIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_study_plan_id not between", value1, value2, "studyPlanId");
            return (Criteria) this;
        }

        public Criteria andPointIsNull() {
            addCriterion("_point is null");
            return (Criteria) this;
        }

        public Criteria andPointIsNotNull() {
            addCriterion("_point is not null");
            return (Criteria) this;
        }

        public Criteria andPointEqualTo(String value) {
            addCriterion("_point =", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotEqualTo(String value) {
            addCriterion("_point <>", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointGreaterThan(String value) {
            addCriterion("_point >", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointGreaterThanOrEqualTo(String value) {
            addCriterion("_point >=", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointLessThan(String value) {
            addCriterion("_point <", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointLessThanOrEqualTo(String value) {
            addCriterion("_point <=", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointLike(String value) {
            addCriterion("_point like", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotLike(String value) {
            addCriterion("_point not like", value, "point");
            return (Criteria) this;
        }

        public Criteria andPointIn(List<String> values) {
            addCriterion("_point in", values, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotIn(List<String> values) {
            addCriterion("_point not in", values, "point");
            return (Criteria) this;
        }

        public Criteria andPointBetween(String value1, String value2) {
            addCriterion("_point between", value1, value2, "point");
            return (Criteria) this;
        }

        public Criteria andPointNotBetween(String value1, String value2) {
            addCriterion("_point not between", value1, value2, "point");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNull() {
            addCriterion("_question is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIsNotNull() {
            addCriterion("_question is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionEqualTo(String value) {
            addCriterion("_question =", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotEqualTo(String value) {
            addCriterion("_question <>", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThan(String value) {
            addCriterion("_question >", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("_question >=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThan(String value) {
            addCriterion("_question <", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLessThanOrEqualTo(String value) {
            addCriterion("_question <=", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionLike(String value) {
            addCriterion("_question like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotLike(String value) {
            addCriterion("_question not like", value, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionIn(List<String> values) {
            addCriterion("_question in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotIn(List<String> values) {
            addCriterion("_question not in", values, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionBetween(String value1, String value2) {
            addCriterion("_question between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andQuestionNotBetween(String value1, String value2) {
            addCriterion("_question not between", value1, value2, "question");
            return (Criteria) this;
        }

        public Criteria andUseCaseIsNull() {
            addCriterion("_use_case is null");
            return (Criteria) this;
        }

        public Criteria andUseCaseIsNotNull() {
            addCriterion("_use_case is not null");
            return (Criteria) this;
        }

        public Criteria andUseCaseEqualTo(String value) {
            addCriterion("_use_case =", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseNotEqualTo(String value) {
            addCriterion("_use_case <>", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseGreaterThan(String value) {
            addCriterion("_use_case >", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseGreaterThanOrEqualTo(String value) {
            addCriterion("_use_case >=", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseLessThan(String value) {
            addCriterion("_use_case <", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseLessThanOrEqualTo(String value) {
            addCriterion("_use_case <=", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseLike(String value) {
            addCriterion("_use_case like", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseNotLike(String value) {
            addCriterion("_use_case not like", value, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseIn(List<String> values) {
            addCriterion("_use_case in", values, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseNotIn(List<String> values) {
            addCriterion("_use_case not in", values, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseBetween(String value1, String value2) {
            addCriterion("_use_case between", value1, value2, "useCase");
            return (Criteria) this;
        }

        public Criteria andUseCaseNotBetween(String value1, String value2) {
            addCriterion("_use_case not between", value1, value2, "useCase");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _study_plan_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _study_plan_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}