package com.dao.beans;

public class StudyPlanDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _study_plan_detail._id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _study_plan_detail._study_plan_id
     *
     * @mbg.generated
     */
    private Integer studyPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _study_plan_detail._point
     *
     * @mbg.generated
     */
    private String point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _study_plan_detail._question
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _study_plan_detail._use_case
     *
     * @mbg.generated
     */
    private String useCase;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _study_plan_detail._id
     *
     * @return the value of _study_plan_detail._id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _study_plan_detail._id
     *
     * @param id the value for _study_plan_detail._id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _study_plan_detail._study_plan_id
     *
     * @return the value of _study_plan_detail._study_plan_id
     *
     * @mbg.generated
     */
    public Integer getStudyPlanId() {
        return studyPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _study_plan_detail._study_plan_id
     *
     * @param studyPlanId the value for _study_plan_detail._study_plan_id
     *
     * @mbg.generated
     */
    public void setStudyPlanId(Integer studyPlanId) {
        this.studyPlanId = studyPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _study_plan_detail._point
     *
     * @return the value of _study_plan_detail._point
     *
     * @mbg.generated
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _study_plan_detail._point
     *
     * @param point the value for _study_plan_detail._point
     *
     * @mbg.generated
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _study_plan_detail._question
     *
     * @return the value of _study_plan_detail._question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _study_plan_detail._question
     *
     * @param question the value for _study_plan_detail._question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _study_plan_detail._use_case
     *
     * @return the value of _study_plan_detail._use_case
     *
     * @mbg.generated
     */
    public String getUseCase() {
        return useCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _study_plan_detail._use_case
     *
     * @param useCase the value for _study_plan_detail._use_case
     *
     * @mbg.generated
     */
    public void setUseCase(String useCase) {
        this.useCase = useCase == null ? null : useCase.trim();
    }
}